"""postgres baseline

Revision ID: 84d605cd8180
Revises: 
Create Date: 2026-03-26 04:09:47.012319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d605cd8180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gst_exempt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pst_exempt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('ix_customer_archived', ['archived'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('event_type', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('estimated_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gl_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchase_order_item_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('favorites', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('notify_transfers', sa.Boolean(), nullable=False),
    sa.Column('items_per_page', sa.Integer(), server_default='20', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('last_forced_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gst_exempt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pst_exempt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_archived', ['archived'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_date_created'), ['date_created'], unique=False)
        batch_op.create_index('ix_invoice_user_id', ['user_id'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.Column('upc', sa.String(length=32), nullable=True),
    sa.Column('gl_code', sa.String(length=10), nullable=True),
    sa.Column('gl_code_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('container_deposit', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('purchase_gl_code_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['gl_code_id'], ['gl_code.id'], ),
    sa.ForeignKeyConstraint(['purchase_gl_code_id'], ['gl_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('ix_item_archived', ['archived'], unique=False)
        batch_op.create_index('uix_item_name_active', ['name'], unique=True, sqlite_where=sa.text('archived = 0'), postgresql_where=sa.text('archived = false'))

    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_spoilage', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('current_menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index('ix_location_archived', ['archived'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_note_pinned', ['entity_type', 'pinned'], unique=False)

    op.create_table('pos_sales_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=False),
    sa.Column('attachment_sha256', sa.String(length=64), nullable=False),
    sa.Column('attachment_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('approval_batch_id', sa.String(length=64), nullable=True),
    sa.Column('reversal_batch_id', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'needs_mapping', 'approved', 'reversed', 'deleted', 'failed')", name='ck_pos_sales_import_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'message_id', 'attachment_sha256', name='uq_pos_sales_import_idempotency')
    )
    with op.batch_alter_table('pos_sales_import', schema=None) as batch_op:
        batch_op.create_index('ix_pos_sales_import_approval_batch', ['approval_batch_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_approved_by', ['approved_by', 'approved_at'], unique=False)
        batch_op.create_index('ix_pos_sales_import_deleted_by', ['deleted_by', 'deleted_at'], unique=False)
        batch_op.create_index('ix_pos_sales_import_received_at', ['received_at'], unique=False)
        batch_op.create_index('ix_pos_sales_import_reversal_batch', ['reversal_batch_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_reversed_by', ['reversed_by', 'reversed_at'], unique=False)
        batch_op.create_index('ix_pos_sales_import_status_received_at', ['status', 'received_at'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gl_code', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('invoice_sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('gl_code_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('recipe_yield_quantity', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('recipe_yield_unit', sa.String(length=50), nullable=True),
    sa.Column('sales_gl_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gl_code_id'], ['gl_code.id'], ),
    sa.ForeignKeyConstraint(['sales_gl_code_id'], ['gl_code.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('expected_total_cost', sa.Float(), nullable=True),
    sa.Column('delivery_charge', sa.Float(), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_sales_resolution_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', 'token_id', name='uq_terminal_sales_state_event_user_token')
    )
    with op.batch_alter_table('terminal_sales_resolution_state', schema=None) as batch_op:
        batch_op.create_index('ix_terminal_sales_state_event_user', ['event_id', 'user_id'], unique=False)

    op.create_table('user_filter_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', name='uq_user_filter_preference_scope')
    )
    op.create_table('event_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('opening_count', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('closing_count', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'location_id', name='_event_loc_uc')
    )
    op.create_table('invoice_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_subtotal', sa.Float(), nullable=False),
    sa.Column('line_gst', sa.Float(), nullable=False),
    sa.Column('line_pst', sa.Float(), nullable=False),
    sa.Column('override_gst', sa.Boolean(), nullable=True),
    sa.Column('override_pst', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'fk_invoice_product_invoice_id_invoice',
        'invoice_product',
        'invoice',
        ['invoice_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_table('item_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('receiving_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('transfer_default', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_products',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'product_id')
    )
    op.create_table('location_stand_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('expected_count', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('purchase_gl_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['purchase_gl_code_id'], ['gl_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'item_id', name='_loc_item_uc')
    )
    op.create_table('menu_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_menu_assignment_active', ['location_id', 'unassigned_at'], unique=False)

    op.create_table('menu_products',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'product_id')
    )
    op.create_table('pos_sales_import_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('source_location_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_location_name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('net_inc', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('discounts_abs', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('computed_total', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('parse_index', sa.Integer(), nullable=False),
    sa.Column('approval_batch_id', sa.String(length=64), nullable=True),
    sa.Column('reversal_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['pos_sales_import.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'parse_index', name='uq_pos_sales_import_location_order')
    )
    with op.batch_alter_table('pos_sales_import_location', schema=None) as batch_op:
        batch_op.create_index('ix_pos_sales_import_location_approval_batch', ['approval_batch_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_location_import', ['import_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_location_location_id', ['location_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_location_normalized', ['normalized_location_name'], unique=False)
        batch_op.create_index('ix_pos_sales_import_location_reversal_batch', ['reversal_batch_id'], unique=False)

    op.create_table('purchase_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('location_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('pst', sa.Float(), nullable=False),
    sa.Column('delivery_charge', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_invoice_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id')
    )
    op.create_table('terminal_sale_location_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('terminal_sale_product_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('from_location_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('to_location_name', sa.String(length=100), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_date_created', ['date_created'], unique=False)
        batch_op.create_index('ix_transfer_to_location_completed', ['to_location_id', 'completed'], unique=False)
        batch_op.create_index('ix_transfer_user_id', ['user_id'], unique=False)

    op.create_table('event_location_terminal_sales_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_location_id', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('variance_details', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_location_id'], ['event_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_location_id')
    )
    op.create_table('event_stand_sheet_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('opening_count', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('transferred_in', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('transferred_out', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('adjustments', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('eaten', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('spoiled', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('closing_count', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['event_location_id'], ['event_location.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_location_id', 'item_id', name='_event_loc_item_uc')
    )
    op.create_table('pos_sales_import_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('location_import_id', sa.Integer(), nullable=False),
    sa.Column('source_product_code', sa.String(length=128), nullable=True),
    sa.Column('source_product_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_product_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('net_inc', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('discount_raw', sa.String(length=64), nullable=True),
    sa.Column('discount_abs', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('computed_line_total', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('computed_unit_price', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('parse_index', sa.Integer(), nullable=False),
    sa.Column('is_zero_quantity', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('approval_batch_id', sa.String(length=64), nullable=True),
    sa.Column('reversal_batch_id', sa.String(length=64), nullable=True),
    sa.Column('approval_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['pos_sales_import.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_import_id'], ['pos_sales_import_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_import_id', 'parse_index', name='uq_pos_sales_import_row_order')
    )
    with op.batch_alter_table('pos_sales_import_row', schema=None) as batch_op:
        batch_op.create_index('ix_pos_sales_import_row_approval_batch', ['approval_batch_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_import', ['import_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_location_import', ['location_import_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_normalized_product', ['normalized_product_name'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_reversal_batch', ['reversal_batch_id'], unique=False)
        batch_op.create_index('ix_pos_sales_import_row_zero_qty', ['is_zero_quantity'], unique=False)

    op.create_table('product_recipe_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('countable', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['item_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('container_deposit', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('prev_cost', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('purchase_gl_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoice.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_gl_code_id'], ['gl_code.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['item_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['item_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_location_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_location_id'], ['event_location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('completed_quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_quantity', sa.Float(), nullable=True),
    sa.Column('base_quantity', sa.Float(), nullable=True),
    sa.Column('item_name', sa.String(length=100), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['item_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_items',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.PrimaryKeyConstraint('transfer_id', 'item_id')
    )
    op.create_table('vendor_item_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_unit_id', sa.Integer(), nullable=True),
    sa.Column('vendor_sku', sa.String(length=100), nullable=True),
    sa.Column('vendor_description', sa.String(length=255), nullable=True),
    sa.Column('normalized_description', sa.String(length=255), nullable=True),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('default_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_unit_id'], ['item_unit.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'normalized_description', name='uq_vendor_item_alias_description'),
    sa.UniqueConstraint('vendor_id', 'vendor_sku', name='uq_vendor_item_alias_sku')
    )
    with op.batch_alter_table('vendor_item_alias', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_item_alias_vendor', ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_item_alias', schema=None) as batch_op:
        batch_op.drop_index('ix_vendor_item_alias_vendor')

    op.drop_table('vendor_item_alias')
    op.drop_table('transfer_items')
    op.drop_table('transfer_item')
    op.drop_table('terminal_sale')
    op.drop_table('purchase_order_item')
    op.drop_table('purchase_invoice_item')
    op.drop_table('product_recipe_item')
    with op.batch_alter_table('pos_sales_import_row', schema=None) as batch_op:
        batch_op.drop_index('ix_pos_sales_import_row_zero_qty')
        batch_op.drop_index('ix_pos_sales_import_row_reversal_batch')
        batch_op.drop_index('ix_pos_sales_import_row_product_id')
        batch_op.drop_index('ix_pos_sales_import_row_normalized_product')
        batch_op.drop_index('ix_pos_sales_import_row_location_import')
        batch_op.drop_index('ix_pos_sales_import_row_import')
        batch_op.drop_index('ix_pos_sales_import_row_approval_batch')

    op.drop_table('pos_sales_import_row')
    op.drop_table('event_stand_sheet_item')
    op.drop_table('event_location_terminal_sales_summary')
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_user_id')
        batch_op.drop_index('ix_transfer_to_location_completed')
        batch_op.drop_index('ix_transfer_date_created')

    op.drop_table('transfer')
    op.drop_table('terminal_sale_product_alias')
    op.drop_table('terminal_sale_location_alias')
    op.drop_table('purchase_invoice_draft')
    op.drop_table('purchase_invoice')
    with op.batch_alter_table('pos_sales_import_location', schema=None) as batch_op:
        batch_op.drop_index('ix_pos_sales_import_location_reversal_batch')
        batch_op.drop_index('ix_pos_sales_import_location_normalized')
        batch_op.drop_index('ix_pos_sales_import_location_location_id')
        batch_op.drop_index('ix_pos_sales_import_location_import')
        batch_op.drop_index('ix_pos_sales_import_location_approval_batch')

    op.drop_table('pos_sales_import_location')
    op.drop_table('menu_products')
    with op.batch_alter_table('menu_assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_assignment_active')

    op.drop_table('menu_assignment')
    op.drop_table('location_stand_item')
    op.drop_table('location_products')
    op.drop_table('item_unit')
    op.drop_constraint('fk_invoice_product_invoice_id_invoice', 'invoice_product', type_='foreignkey')
    op.drop_table('invoice_product')
    op.drop_table('event_location')
    op.drop_table('user_filter_preference')
    with op.batch_alter_table('terminal_sales_resolution_state', schema=None) as batch_op:
        batch_op.drop_index('ix_terminal_sales_state_event_user')

    op.drop_table('terminal_sales_resolution_state')
    op.drop_table('purchase_order')
    op.drop_table('product')
    with op.batch_alter_table('pos_sales_import', schema=None) as batch_op:
        batch_op.drop_index('ix_pos_sales_import_status_received_at')
        batch_op.drop_index('ix_pos_sales_import_reversed_by')
        batch_op.drop_index('ix_pos_sales_import_reversal_batch')
        batch_op.drop_index('ix_pos_sales_import_received_at')
        batch_op.drop_index('ix_pos_sales_import_deleted_by')
        batch_op.drop_index('ix_pos_sales_import_approved_by')
        batch_op.drop_index('ix_pos_sales_import_approval_batch')

    op.drop_table('pos_sales_import')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_pinned')
        batch_op.drop_index('ix_note_entity')

    op.drop_table('note')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('ix_location_archived')

    op.drop_table('location')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('uix_item_name_active', sqlite_where=sa.text('archived = 0'), postgresql_where=sa.text('archived = false'))
        batch_op.drop_index('ix_item_archived')

    op.drop_table('item')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_user_id')
        batch_op.drop_index(batch_op.f('ix_invoice_date_created'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    op.drop_table('activity_log')
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index('ix_vendor_archived')

    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('purchase_order_item_archive')
    op.drop_table('menu')
    op.drop_table('gl_code')
    op.drop_table('event')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_archived')

    op.drop_table('customer')
    # ### end Alembic commands ###
